// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAic86i4vTTeIuxBMqUBnKDSle-YElsMfM',
    appId: '1:112730238756:web:30b7b3694dffdcae370db1',
    messagingSenderId: '112730238756',
    projectId: 'entrix-con-firabase',
    authDomain: 'entrix-con-firabase.firebaseapp.com',
    storageBucket: 'entrix-con-firabase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA8_y1Nn_OMsJZ4P8p07Aw7YBbGaDb5kw',
    appId: '1:112730238756:android:31a61fb06d2bc1f4370db1',
    messagingSenderId: '112730238756',
    projectId: 'entrix-con-firabase',
    storageBucket: 'entrix-con-firabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_88puzzdTFmyj09r56hkuUA5vxEhA_U',
    appId: '1:112730238756:ios:3bf3e2189d944e26370db1',
    messagingSenderId: '112730238756',
    projectId: 'entrix-con-firabase',
    storageBucket: 'entrix-con-firabase.firebasestorage.app',
    androidClientId: '112730238756-42dgm5eopjkr9h7j4tsebn0sim03m38a.apps.googleusercontent.com',
    iosClientId: '112730238756-uco56rmjuqti2mqb9vdahv8mi839fac3.apps.googleusercontent.com',
    iosBundleId: 'com.example.entrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_88puzzdTFmyj09r56hkuUA5vxEhA_U',
    appId: '1:112730238756:ios:3bf3e2189d944e26370db1',
    messagingSenderId: '112730238756',
    projectId: 'entrix-con-firabase',
    storageBucket: 'entrix-con-firabase.firebasestorage.app',
    androidClientId: '112730238756-42dgm5eopjkr9h7j4tsebn0sim03m38a.apps.googleusercontent.com',
    iosClientId: '112730238756-uco56rmjuqti2mqb9vdahv8mi839fac3.apps.googleusercontent.com',
    iosBundleId: 'com.example.entrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAic86i4vTTeIuxBMqUBnKDSle-YElsMfM',
    appId: '1:112730238756:web:6c794b4431b8529b370db1',
    messagingSenderId: '112730238756',
    projectId: 'entrix-con-firabase',
    authDomain: 'entrix-con-firabase.firebaseapp.com',
    storageBucket: 'entrix-con-firabase.firebasestorage.app',
  );

}